import { boolean, date, integer, numeric, pgTable, text, timestamp, unique } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull(), image: text('image'), createdAt: timestamp('createdAt').notNull(), updatedAt: timestamp('updatedAt').notNull() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull(), updatedAt: timestamp('updatedAt').notNull(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull(), updatedAt: timestamp('updatedAt').notNull() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt'), updatedAt: timestamp('updatedAt') })
export const challenge = pgTable('challenge', { id: text('id').primaryKey(), ownerId: text('ownerId').notNull(), name: text('name').notNull(), goalType: text('goalType').notNull(), goalValue: numeric('goalValue'), startDate: date('startDate').notNull(), endDate: date('endDate').notNull(), joinCode: text('joinCode').notNull().unique(), createdAt: timestamp('createdAt').notNull() })
export const challengeMember = pgTable('challenge_member', { id: text('id').primaryKey(), challengeId: text('challengeId').notNull(), userId: text('userId').notNull(), joinedAt: timestamp('joinedAt').notNull() }, (t) => [unique().on(t.challengeId, t.userId)])
export const cardioRecord = pgTable('cardio_record', { id: text('id').primaryKey(), challengeId: text('challengeId'), userId: text('userId').notNull(), recordDate: date('recordDate').notNull(), minutes: integer('minutes').notNull(), kilometers: numeric('kilometers').notNull(), pace: numeric('pace'), activityType: text('activityType').notNull(), proofPathname: text('proofPathname').notNull(), description: text('description'), createdAt: timestamp('createdAt').notNull() }, (t) => [unique().on(t.userId, t.recordDate)])

export const authSchema = { user, session, account, verification }
export const appSchema = { challenge, challengeMember, cardioRecord }
